$schema = "./node_modules/wrangler/config-schema.json"

name = "caseflow"
compatibility_date = "2026-03-17"
pages_build_output_dir = "./dist"

[vars]
APP_NAME = "CaseFlow"
AUTH_USERNAME = "hbhklaw"
AUTH_PASSWORD = "barnes"
SESSION_SECRET = "whoelectedyouleaderofthisoutfit"

[[d1_databases]]
binding = "DB"
database_name = "caseflow-prod"
database_id = "259331b8-6e54-4cb5-af0b-e62d1eefb72d"
